language: bash

matrix:
  include:
  - name: "Documentation"
    language: python
    os: linux
    python:
      - "3.6"
    branches:
      only:
        - master
        - dev
    addons:
      apt:
        packages:
          - doxygen
          - graphviz
    install:
      - pip install sphinx sphinx_rtd_theme breathe sphinx_tabs
    script:
      - |
        cd doc
        mkdir _build
        doxygen
        make html
        touch _build/html/.nojekyll
        cd -
    deploy:
      provider: pages
      repo: hi2p-perim/lightmetrica-v3-doc
      local_dir: doc/_build/html
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      keep_history: false
      target-branch: master
      on:
        all_branches: true

  - name: "Build on Linux environment with Docker"
    os: linux
    services: docker
    before_install:
    - git clone https://$GITHUB_TOKEN@github.com/hi2p-perim/lightmetrica-v3-scenes.git scenes
    script:
    - docker build -t lm3 .
    - docker run --rm -it -v $TRAVIS_BUILD_DIR:/lm3 lm3 sh -c 'cd /lightmetrica-v3 && python3 ./example/run_all.py --lm ./_build/bin --outdir /lm3/example_results --scene /lm3/scenes --spp 10 --width 640 --height 360'
    - docker run --rm -it -v $TRAVIS_BUILD_DIR:/lm3 lm3 sh -c 'cd /lightmetrica-v3 && python3 ./example/run_all_py.py --outdir /lm3/example_results --scene /lm3/scenes --spp 10 --width 640 --height 360'
    - docker run --rm -it -v ${PWD}:/lm3 lm3 bash -c "cd /lightmetrica-v3 && python3 ./example/compress_images.py --dir /lm3/example_results"
    deploy:
      provider: pages
      repo: hi2p-perim/lightmetrica-v3-artifact
      local_dir: example_results
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      keep_history: false
      target-branch: master
      on:
        all_branches: true

  - name: "Build on Windows environment"
    os: windows
    dist: 1803-containers
    # Workaround for https://travis-ci.community/t/choco-install-hangs-forever/307/20
    filter_secrets: false
    before_install:
    - |
      choco install miniconda3
      export PATH="/c/Tools/miniconda3/Scripts:$PATH"
      conda update -y -n base -c defaults conda
      conda create -y -n lm3 python=3.6 
      source activate lm3
      conda install -y pytest numpy
    install:
    - |
      cd ${TRAVIS_BUILD_DIR}
      mkdir external && cd external
      git clone --depth 1 --branch v2.2.4 https://github.com/pybind/pybind11.git
      git clone --depth 1 --branch v3.5.0 https://github.com/nlohmann/json.git
      git clone --depth 1 --branch 0.9.9.3 https://github.com/g-truc/glm.git
      git clone --depth 1 --branch v1.2.2 https://github.com/USCiLab/cereal.git
      git clone --depth 1 --branch 2.2.0 https://github.com/onqtam/doctest.git
      git clone --depth 1 --branch 5.3.0 https://github.com/fmtlib/fmt.git
      git clone --depth 1 --branch v4.3.0 https://github.com/zeromq/libzmq.git
      git clone --depth 1 --branch v4.3.0 https://github.com/zeromq/cppzmq.git
      git clone --depth 1 --branch v1.67 https://github.com/ocornut/imgui.git
      git clone --depth 1 --branch 3.2.1 https://github.com/glfw/glfw.git
    script:
    - |
      cd ${TRAVIS_BUILD_DIR}
      cmake -G "Visual Studio 15 2017 Win64" -H. -B_build -DCMAKE_BUILD_TYPE=Release
      cmake --build _build --config Release
      cd _build/bin/Release
      ./lm_test.exe
      cd ${TRAVIS_BUILD_DIR}
      python -m pytest --lm _build/bin/Release pytest
