matrix:
  include:
  - name: "Documentation"
    language: python
    os: linux
    python:
      - "3.6"
    branches:
      only:
        - master
        - dev
    addons:
      apt:
        packages:
          - doxygen
          - graphviz
    install:
      - pip install sphinx sphinx_rtd_theme breathe sphinx_tabs
    script:
      - |
        cd doc
        doxygen
        make html
        touch _build/html/.nojekyll
        cd -
    deploy:
      provider: pages
      repo: hi2p-perim/lightmetrica-v3-doc
      local_dir: doc/_build/html
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      keep_history: false
      target-branch: master
      on:
        all_branches: true

  - name: "Build on Linux environment with Docker"
    language: bash
    os: linux
    services: docker
    script:
    - docker build -t lm3 .

  - name: "Build on Windows environment"
    language: bash
    os: windows
    dist: 1803-containers
    before_install:
    - |
      choco install miniconda3
      /c/Tools/miniconda3/Scripts/conda update -y -n base -c defaults conda
      /c/Tools/miniconda3/Scripts/conda create -y -n lm3 python=3.6 
      source /c/Tools/miniconda3/Scripts/activate lm3
      /c/Tools/miniconda3/Scripts/conda install -y pytest numpy
    install:
    - |
      cd ${TRAVIS_BUILD_DIR}
      mkdir external && cd external
      git clone --depth 1 --branch v2.2.4 https://github.com/pybind/pybind11.git
      git clone --depth 1 --branch v3.5.0 https://github.com/nlohmann/json.git
      git clone --depth 1 --branch 0.9.9.3 https://github.com/g-truc/glm.git
      git clone --depth 1 --branch v1.2.2 https://github.com/USCiLab/cereal.git
      git clone --depth 1 --branch 2.2.0 https://github.com/onqtam/doctest.git
      git clone --depth 1 --branch 5.3.0 https://github.com/fmtlib/fmt.git
    script:
    - |
      cd ${TRAVIS_BUILD_DIR}
      cmake -G "Visual Studio 15 2017 Win64" -H. -B_build -DCMAKE_BUILD_TYPE=Release
      cmake --build _build --config Release
      cd _build/bin/Release
      ./lm_test.exe
      cd ${TRAVIS_BUILD_DIR}
      python -m pytest --lm _build/bin/Release pytest
