name: lm3_dev
channels:
  # hi2p-perim channel must have higher priority
  # because some packages might have the same names.
  - hi2p-perim
  - conda-forge
dependencies:
  - python=3.7
  - cmake
  - jupyter
  - matplotlib
  - scipy
  - pandas
  - sphinx
  - sphinx_rtd_theme
  - jupytext
  - tqdm
  - colorama
  - imageio
  - pytest
  - zeromq
  - cppzmq
  - pybind11
  - embree3
  - glfw
  - glm
  - nlohmann_json
  - glew
  - doctest-cpp
  - fmt
  - stb
  - cereal
  - vdbloader
  - tbb-devel
  - pbrt-parser
  - pip:
    - sphinx-autobuild
    - breathe
    - sphinx_tabs
    - nbsphinx
    - nbmerge